#vars
ENGINE=phoenix/Makefile
GAME=GamePlayground/Makefile

#Compiles all the files 
all: debug build

build:
	make $(ENGIN)E build
	make $(GAME) build
debug:
	make $(ENGINE) debug
	make $(GAME) debug
clean:
	rm -rf *.o build/ debug/
	
cleano:
	rm -rf *.o




